<script language="JavaScript">
<!--
document.writeln("<!DOCTYPE html>");
document.writeln("html lang=/"en/">");
document.writeln("head>");
document.writeln("   <meta charset=/"UTF-8/">");
document.writeln("   <meta name=/"viewport/" content=/"width=device-width, initial-scale=1.0/">");
document.writeln("   <title>Live Match Updates</title>");
document.writeln("   <style>");
document.writeln("       /* Styling for the image card1 container */");
document.writeln("       .card1 {");
document.writeln("           width: 100%;");
document.writeln("           margin: 0px;");
document.writeln("           border: 2px solid #ddd; /* Border around the card1 */");
document.writeln("           border-radius: 10px; /* Rounded corners */");
document.writeln("           overflow: hidden;");
document.writeln("           box-shadow: 0 8px 16px rgba(0, 0, 0, 0.7);");
document.writeln("           position: relative;");
document.writeln("           background-color: white;");
document.writeln("           transition: transform 0.3s ease;");
document.writeln("       }");
document.writeln("        .card1:hover {");
document.writeln("           transform: translateY(-10px); /* Slightly raise card1 on hover */");
document.writeln("       }");
document.writeln("        /* Styling for hoverable images */");
document.writeln("       .card1 img {");
document.writeln("           width: 100%;");
document.writeln("           height: auto;");
document.writeln("           display: block;");
document.writeln("           transition: opacity 0.3s ease;");
document.writeln("       }");
document.writeln("        /* caption1 styling */");
document.writeln("       .caption1 {");
document.writeln("           padding: 10px;");
document.writeln("           text-align: center;");
document.writeln("           font-size: 23px;");
document.writeln("           color: green;");
document.writeln("           background-color: black;");
document.writeln("           border-top: 1px solid #ddd;");
document.writeln("           font-weight: bold; /* Make the title bold */");
document.writeln("       }");
document.writeln("        /* description1 styling */");
document.writeln("       .description1 {");
document.writeln("           font-size: 15px;");
document.writeln("           color: yellow; /* Slightly gray color for description1 */");
document.writeln("           margin-top: 5px;");
document.writeln("       }");
document.writeln("        /* Countdown Timer Styling */");
document.writeln("       .countdown-timer {");
document.writeln("           position: absolute;");
document.writeln("           bottom: 10px;");
document.writeln("           right: 10px; /* Align the countdown timer to the top right corner */");
document.writeln("           background-color: rgba(0, 0, 0, 0.7);");
document.writeln("           color: white;");
document.writeln("           font-size: 14px;");
document.writeln("           padding: 0px 0px;");
document.writeln("           border-radius: 5px;");
document.writeln("       }");
document.writeln("        /* Styling for blinking /"Live Now/" button */");
document.writeln("       .blink-button1 {");
document.writeln("           position: absolute;");
document.writeln("           bottom: 10px;");
document.writeln("           right: 10px;");
document.writeln("           padding: 2px 5px;");
document.writeln("           background-color: red;");
document.writeln("           color: white;");
document.writeln("           font-size: 16px;");
document.writeln("           font-weight: bold;");
document.writeln("           border: none;");
document.writeln("           border-radius: 5px;");
document.writeln("           cursor: pointer;");
document.writeln("           display: none; /* Hidden by default */");
document.writeln("       }");
document.writeln("        .blink-button1:hover {");
document.writeln("           background-color: darkred;");
document.writeln("       }");
document.writeln("        /* Blinking animation */");
document.writeln("       @keyframes blink {");
document.writeln("           0%, 100% { opacity: 1; }");
document.writeln("           50% { opacity: 0; }");
document.writeln("       }");
document.writeln("        .blink-button1 {");
document.writeln("           animation: blink 0.5s infinite; /* Faster blinking effect (0.5s) */");
document.writeln("       }");
document.writeln("/* Hide underline in links */");
document.writeln("       .card1 a {");
document.writeln("           text-decoration: none;");
document.writeln("       }");
document.writeln("       /* Ensure responsiveness */");
document.writeln("       @media (max-width: 600px) {");
document.writeln("           .card1 {");
document.writeln("               width: 100%; /* Adjust card1 width on small screens */");
document.writeln("           }");
document.writeln("       }");
document.writeln("   </style>");
document.writeln("   <script>");
document.writeln("       // Set the future event time (adjust the date and time)");
document.writeln("       const eventTime = new Date('Feb 27, 2025 13:30:00'); // Set the event date and time");
document.writeln("        // Function to update the countdown timer");
document.writeln("       function updateCountdownTimer() {");
document.writeln("           const currentTime = new Date();");
document.writeln("           const timeRemaining = eventTime - currentTime;");
document.writeln("            if (timeRemaining <= 0) {");
document.writeln("               // Hide countdown timer and show the /"Live Now/" button");
document.writeln("               document.getElementById('countdown-timer').style.display = 'none'; // Hide countdown timer");
document.writeln("               document.getElementById('live-button').style.display = 'inline-block'; // Show Live Now button");
document.writeln("               return;");
document.writeln("           }");
document.writeln("            const days = Math.floor(timeRemaining / (1000 * 60 * 60 * 24));");
document.writeln("           const hours = Math.floor((timeRemaining % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));");
document.writeln("           const minutes = Math.floor((timeRemaining % (1000 * 60 * 60)) / (1000 * 60));");
document.writeln("           const seconds = Math.floor((timeRemaining % (1000 * 60)) / 1000);");
document.writeln("            document.getElementById('countdown-timer').innerHTML = ");
document.writeln("               days + /"d /" + hours + /"h /" + minutes + /"m /" + seconds + /"s /";");
document.writeln("       }");
document.writeln("        // Run the check function every second to update countdown in real time");
document.writeln("       setInterval(updateCountdownTimer, 1000); // Update every second (1000 ms)");
document.writeln("        // Run the check function on page load");
document.writeln("       window.onload = function() {");
document.writeln("           updateCountdownTimer(); // Update timer immediately on page load");
document.writeln("       }");
document.writeln("        // Function to open a link in a new tab");
document.writeln("       function openLink(url) {");
document.writeln("           window.open(url, '_blank'); // Open the link in a new tab");
document.writeln("       }");
document.writeln("   </script>");
document.writeln("/head>");
document.writeln("body>");
document.writeln("   <!-- Image card1 with caption1, Bold Title, and description1 -->");
document.writeln("   <div class=/"card1/"><a href=/"https://bindaaslinks.com/zToP1yuE/">");
document.writeln("       <img src=/"https://iili.io/3dAQ1oP.md.jpg/" ");
document.writeln("            alt=/"INDIA vs ENGLAND/" >");
document.writeln("       <div class=/"caption1/">");
document.writeln("           Pakistan vs Bangladesh");
document.writeln("           <p class=/"description1/">");
document.writeln("              | ODI Champions 🏆| Match 9 |");
document.writeln("           </p>");
document.writeln("       </div>");
document.writeln("       <div class=/"countdown-timer/" id=/"countdown-timer/"></div> <!-- Countdown Timer -->");
document.writeln("       <button class=/"blink-button1/" id=/"live-button/">Live Now</button> </a><!-- Live Now Button -->");
document.writeln("   </div>");
document.writeln("/body>");
document.writeln("/html>");
document.writeln("");
document.writeln("!------->");
//-->
</script>
